#!/bin/bash

#################################
# subl
#
# Sublime opener for mac
#
# @date 2015.08.09
# @author Luavis
# @license MIT
#################################

print_bold() {
  printf "\033[1m$1\033[0m"
}

echo_bold() {
  printf "\033[1m$1\033[0m\n"
}

print_help() {
  echo_bold "\033[1mUsage\033[0m:"
  echo "  subl [<existed file> | <new file> | <existed dir>] [-v] [-h] [-d <existed dir>|<new dir name>] [-f <existed file> | <new file>]"
  echo
  echo_bold "Options:"
  printf "  \033[1m%-25s\033[0m %-25s\n" "-v" "create or open directory with sublime text"
  printf "  \033[1m%-25s\033[0m %-25s\n" "-d" "create or open directory with sublime text"
  printf "  \033[1m%-25s\033[0m %-25s\n" "-f" "create or open file with sublime text"
  printf "  \033[1m%-25s\033[0m %-25s\n" "-h[, --help]" "create or open directory with sublime"
}

open_with_sublime() {

}

create_dir() {
  mkdir -p $1
}

create_file() {
  file=$1
  mkdir -p -- "${file%/*}" && touch -- "$file"
}

parse_options() {
  options=( "$@" )
  options_len=${#options[@]}

  sublime_option=""
  mode="file" # defualt mode(create or open) is file

  for (( i=0; i<${options_len}; i++ )); do
    if [ mode = 'file' ]; then 
      if ! [[ -f options[$i] ]]; then
        create_file options[$i]
      fi
    elif [ mode = 'dir' ]; then
      if ! [[ -d options[$i] ]]; then
        create_dir options[$i]
      fi
    fi

    sublime_option="${sublime_option} ${options[$i]}"  # concat string
  done

  open_with_sublime $sublime_option
}

main() {

  if [[ $# = 0 ]]; then
      print_help
  elif [ $1 = '--help' -o  $1 = '-h' ]; then
    print_help
  else
    parse_options "$@"
  fi
}

main "$@"
