#!/bin/bash

#################################
# subl
#
# Sublime opener for mac
#
# @date 2015.08.09
# @author Luavis
# @license MIT
#################################

print_bold() {
  printf "\033[1m$1\033[0m"
}

echo_bold() {
  printf "\033[1m$1\033[0m\n"
}

print_help() {
  echo_bold "\033[1mUsage\033[0m:"
  echo "  subl [<existed file> | <new file> | <existed dir>] [-d <existed dir>|<new dir name>] [-f <existed file> | <new file>]"
  echo
  echo_bold "Options:"
  printf "  \033[1m%-25s\033[0m %-25s\n" "-d" "create or open directory with sublime text"
  printf "  \033[1m%-25s\033[0m %-25s\n" "-f" "create or open file with sublime text"
  printf "  \033[1m%-25s\033[0m %-25s\n" "-h[, --help]" "create or open directory with sublime"
}

# open_with_sublime() {

# }

create_dir() {
  mkdir -p $1
}

parse_options() {
  options=( "$@" )
  options_len=${#options[@]}

  sublime_option=""

  for (( i=0; i<${options_len}; i++ )); do
    echo "${options[$i]}"

    sublime_option="${sublime_option} ${}"
  done
}

main() {

  if [[ $# = 0 ]]; then
      print_help
  elif [ $1 = '--help' -o  $1 = '-h' ]; then
    print_help
  else
    parse_options "$@"
  fi
}

main "$@"
